name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./DNSPod4NETCore2/bin/release/*.nupkg -s https://nuget.pkg.github.com/lishewen/index.json -k ${{ secrets.GITHUB_TOKEN }}
